CREATE DATABASE IF NOT EXISTS p3_aufildeleau;
USE p3_aufildeleau;

CREATE TABLE IF NOT EXISTS items (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS user (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  adress VARCHAR(255) NOT NULL
);
